name: Deploy on Release

on:
  release:
    types: [created]

jobs:
  call-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deployment Webhook
        run: |
          curl -X POST ${{ secrets.WEBHOOK_URL }} \
          -H 'Content-Type: application/json' \
          -d '{"message": "A new release has been created: ${GITHUB_REF_NAME}"}'
